name: chasinaidil
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  flutter_localization: ^0.1.9
  flutter_localizations:
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  isar_generator: ^3.0.5

flutter: 
  uses-material-design: true

