name: chasinaidil
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  flutter_localization: ^0.1.9
  flutter_localizations:
    sdk: flutter
  gesture_x_detector: ^1.1.1
  get_storage: ^2.0.3

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  isar_generator: ^3.0.5
  package_rename: ^1.0.0+1

flutter: 
  uses-material-design: true

  assets:
   - assets/chasinaidil/songs.json
   - assets/chasinaidil/text/
   - assets/chasinaidil/covers/

  fonts:
    - family: UbuntuMono
      fonts:
        - asset: fonts/UbuntuMono-Regular.ttf
        - asset: fonts/UbuntuMono-Italic.ttf
          style: italic
        - asset: fonts/UbuntuMono-Bold.ttf
          weight: 700
        - asset: fonts/UbuntuMono-BoldItalic.ttf
          style: italic
          weight: 700
    - family: NotoSansMono
      fonts:
        - asset: fonts/NotoSansMono-Regular.ttf
        - asset: fonts/NotoSansMono-Bold.ttf
          weight: 700

package_rename_config:
  android:
    app_name: chasinaiDilNew
    package_name: one.nasroni.chasinaidilNew
  ios:
    app_name: chasinaiDil
    bundle_name: chasinaidil
    package_name: one.nasroni.chasinaidil